### ISSUE TITLE
Hide data constructors?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-catenable-lists#16]

**Comment by garyb** [comment]
What does that gain? Are there invariants that need protecting?

**Comment by matthewleon** [comment]
Absent a reason _not_ to do it, it seems to me that hiding the constructors is a sensible default practice. It means that you can change the implementation of the data type without causing a breaking change.

**Comment by garyb** [comment]
@joneshf would like to have a word with anyone who does that without a concrete reason to do so :wink:

(I tend to agree: the argument is, if you do that, and the library doesn't provide the necessary ability to do something, you're screwed. If the constructors are exported, at least you still have the option to do it yourself)

**Comment by matthewleon** [comment]
> if you do that, and the library doesn't provide the necessary ability to do something, you're screwed.

Well, you can fork it. And if the functionality is important, that is probably the right thing, long term... But the ergonomics around that are less than ideal, admittedly. It would be nice if there were some better solution around this, but I suppose I'm derailing at this point.

**Comment by JordanMartinez** [comment]
I think this issue should be closed until a reason justifying this proposal (at least a reason better than "why not?") can be given
